version: '3.8'

services:
  # PostgreSQL數據庫
  postgres:
    image: postgres:16-alpine
    container_name: ticket_knowledge_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_knowledge_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis緩存
  redis:
    image: redis:7-alpine
    container_name: ticket_knowledge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Ticket API服務
  ticket_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_knowledge_ticket_api
    command: uvicorn src.backend.ticket_api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ticket_knowledge_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # Knowledge API服務
  knowledge_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_knowledge_knowledge_api
    command: uvicorn src.backend.knowledge_api.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ticket_knowledge_db
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=your_secret_key_here
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # Elasticsearch全文搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: ticket_knowledge_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped

  # Kibana (Elasticsearch管理界面)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: ticket_knowledge_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  # pgAdmin (PostgreSQL管理界面)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket_knowledge_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: